name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.9']

    steps:
    - uses: actions/checkout@v3
    - name: Use python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        source testing-env/bin/activate
    - name: run Tests
      run: python3 -m unittest __tests__/date_test.py __tests__/evaluation_test.py __tests__/scrape_test.py __tests__/render_daily_report_test.py -v
